project_id = "ymvubgjzyixdlnzahgds"

[functions.create-payment]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.check-admin]
verify_jwt = true

[functions.generate-contract-pdf]
verify_jwt = false
